export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_RECEIVE = "LOG_IN_RECEIVE";
export const FORGET_PASSWORD_RESET_LINK_REQUEST =
  "FORGET_PASSWORD_RESET_LINK_REQUEST";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST";
