export const REQUEST_PROFILE_INFO = "REQUEST_PROFILE_INFO";
export const RECEIVE_PROFILE_INFO = "RECEIVE_PROFILE_INFO";
export const EDIT_PROFILE_INFO_SUBMIT = "EDIT_PROFILE_INFO_SUBMIT";
export const CHANGE_EMAIL_SUBMIT = "CHANGE_EMAIL_SUBMIT";
export const CONFIRM_EMAIL_CHANGE_REQUEST = "CONFIRM_EMAIL_CHANGE_REQUEST";
